export const techCategories = [
  {
    title: 'AI Coding Tools',
    technologies: [
      {id: 'ai_coding_cursor', value: 'Cursor'},
      {id: 'ai_coding_windsurf', value: 'Windsurf'},
      {id: 'ai_coding_zed', value: 'Zed'},
      {id: 'ai_coding_jetbrains_ai', value: 'JetBrains AI'},
      {id: 'ai_coding_jetbrains_junie', value: 'JetBrains Junie'},
      {id: 'ai_coding_cline', value: 'Cline (formerly Claude Dev)'},
      {id: 'ai_coding_supermaven', value: 'Supermaven'},
      {id: 'ai_coding_trae', value: 'Trae'},
      {id: 'ai_coding_neovim', value: 'Neovim'},
      {id: 'ai_coding_chatgpt', value: 'ChatGPT'},
      {id: 'ai_coding_chatgpt_plus', value: 'ChatGPT Plus'},
      {id: 'ai_coding_mistral_ai', value: 'Mistral AI'},
      {id: 'ai_coding_codestral', value: 'Codestral'},
      {id: 'ai_coding_ollama', value: 'Ollama (local)'},
      {id: 'ai_coding_claude', value: 'Claude'},
      {id: 'ai_coding_perplexity', value: 'Perplexity'},
      {id: 'ai_coding_tabnine', value: 'Tabnine'},
      {id: 'ai_coding_vscode', value: 'Vscode'},
      {id: 'ai_coding_github_copilot', value: 'GitHub Copilot'},
      {id: 'ai_coding_codeium', value: 'Codeium'},
      {id: 'ai_coding_codium', value: 'Codium'},
      {id: 'ai_coding_codegpt', value: 'CodeGPT'},
      {id: 'ai_coding_amazon_q', value: 'Amazon Q'},
    ],
  },
  {
    title: 'Web Frontend',
    technologies: [
      {id: 'web_frontend_react', value: 'React'},
      {id: 'web_frontend_nextjs', value: 'Next.js'},
      {id: 'web_frontend_astro', value: 'Astro'},
      {id: 'web_frontend_vue', value: 'Vue.js'},
      {id: 'web_frontend_angular', value: 'Angular'},
      {id: 'web_frontend_htmx', value: 'HTMX'},
      {id: 'web_frontend_svelte', value: 'Svelte'},
      {id: 'web_frontend_nuxt', value: 'Nuxt.js'},
      // {id: 'web_frontend_qwik', value: 'Qwik'},
      // {id: 'web_frontend_solid', value: 'SolidJS'},
      // {id: 'web_frontend_webpack', value: 'Webpack'},
      // {id: 'web_frontend_vite', value: 'Vite'},
      // {id: 'web_frontend_parcel', value: 'Parcel'},
    ],
  },
  {
    title: 'Web Frontend Storage',
    technologies: [
      {id: 'web_frontend_storage_legend', value: 'Legend'},
      {id: 'web_frontend_storage_zustand', value: 'Zustand'},
      {id: 'web_frontend_storage_redux', value: 'Redux'},
      // {id: 'web_frontend_storage_jotai', value: 'Jotai'},
      // {id: 'web_frontend_storage_recoil', value: 'Recoil'},
      {id: 'web_frontend_storage_mobx', value: 'MobX'},
    ],
  },
  {
    title: 'Web Frontend UI Libraries',
    technologies: [
      {id: 'web_frontend_ui_tailwind', value: 'Tailwind'},
      {id: 'web_frontend_ui_chakra', value: 'Chakra UI'},
      {id: 'web_frontend_ui_shadcn', value: 'shadcn/ui'},
      {id: 'web_frontend_ui_antdesign', value: 'Ant Design'},
      {id: 'web_frontend_ui_sass', value: 'Sass'},
      {id: 'web_frontend_ui_materialui', value: 'Material UI'},
      {id: 'web_frontend_ui_daisyui', value: 'Daisy UI'},
      {id: 'web_frontend_ui_bootstrap', value: 'Bootstrap'},
    ],
  },
  {
    title: 'Mobile',
    technologies: [
      {id: 'mobile_expo', value: 'Expo'},
      {id: 'mobile_ios', value: 'iOS (Native)'},
      {id: 'mobile_android', value: 'Android (Native)'},
      {id: 'mobile_react_native', value: 'React Native'},
      {id: 'mobile_flutter', value: 'Flutter'},
    ],
  },
  {
    title: 'Backend',
    technologies: [
      {id: 'backend_nodejs', value: 'Node.js'},
      {id: 'backend_express', value: 'Express'},
      {id: 'backend_django', value: 'Django'},
      {id: 'backend_go', value: 'Go'},
      {id: 'backend_flask', value: 'Flask'},
      {id: 'backend_spring', value: 'Spring'},
      {id: 'backend_rails', value: 'Rails'},
    ],
  },
  {
    title: 'SaaS',
    technologies: [
      {id: 'saas_firebase', value: 'Firebase'},
      {id: 'saas_supabase', value: 'Supabase'},
      {id: 'saas_pocketbase', value: 'PocketBase'},
      {id: 'saas_clerk', value: 'Clerk'},
      {id: 'saas_auth0', value: 'Auth0'},
      {id: 'saas_magic', value: 'Magic'},
      {id: 'saas_sanity', value: 'Sanity.io'},
      {id: 'saas_strapi', value: 'Strapi'},
      {id: 'saas_directus', value: 'Directus'},
      // {id: 'saas_nhost', value: 'Nhost'},
      {id: 'saas_ghost', value: 'Ghost'},
      {id: 'saas_moralis', value: 'Moralis'},
    ],
  },
  {
    title: 'Database',
    technologies: [
      {id: 'database_postgres', value: 'PostgreSQL'},
      {id: 'database_mysql', value: 'MySQL'},
      {id: 'database_mongodb', value: 'MongoDB'},
      {id: 'database_redis', value: 'Redis'},
      {id: 'database_firestore', value: 'Firestore'},
      {id: 'database_dynamodb', value: 'DynamoDB'},
      {id: 'database_sqlite', value: 'SQLite'},
      {id: 'database_oracle', value: 'Oracle'},
      // {id: 'database_neo4j', value: 'Neo4j'},
      {id: 'database_cassandra', value: 'Cassandra'},
    ],
  },
  {
    title: 'Task Management',
    technologies: [
      {id: 'task_management_jira', value: 'Jira'},
      {id: 'task_management_notion', value: 'Notion'},
      {id: 'task_management_asana', value: 'Asana'},
      {id: 'task_management_trello', value: 'Trello'},
      {id: 'task_management_clickup', value: 'ClickUp'},
      {id: 'task_management_monday', value: 'Monday.com'},
      {id: 'task_management_linear', value: 'Linear'},
      {id: 'task_management_basecamp', value: 'Basecamp'},
    ],
  },
  {
    title: 'Git Hosting',
    technologies: [
      {id: 'git_hosting_github', value: 'GitHub'},
      {id: 'git_hosting_gitlab', value: 'GitLab'},
      {id: 'git_hosting_bitbucket', value: 'Bitbucket'},
      {id: 'git_hosting_azure_devops', value: 'Azure DevOps'},
      {id: 'git_hosting_gitea', value: 'Gitea'},
    ],
  },
  // {
  //   title: 'Languages',
  //   technologies: [
  //     {id: 'languages_typescript', value: 'TypeScript'},
  //     {id: 'languages_javascript', value: 'JavaScript'},
  //     {id: 'languages_python', value: 'Python'},
  //     {id: 'languages_java', value: 'Java'},
  //     {id: 'languages_kotlin', value: 'Kotlin'},
  //     {id: 'languages_swift', value: 'Swift'},
  //     {id: 'languages_csharp', value: 'C#'},
  //     {id: 'languages_cpp', value: 'C++'},
  //     {id: 'languages_rust', value: 'Rust'},
  //     {id: 'languages_go', value: 'Go'},
  //     {id: 'languages_ruby', value: 'Ruby'},
  //     {id: 'languages_php', value: 'PHP'},
  //     {id: 'languages_dart', value: 'Dart'},
  //     {id: 'languages_sql', value: 'SQL'},
  //   ],
  // },
  // {
  //   title: 'DevOps',
  //   technologies: [
  //     {id: 'devops_docker', value: 'Docker'},
  //     {id: 'devops_kubernetes', value: 'Kubernetes'},
  //     {id: 'devops_aws', value: 'AWS'},
  //     {id: 'devops_gcp', value: 'GCP'},
  //     {id: 'devops_azure', value: 'Azure'},
  //     {id: 'devops_terraform', value: 'Terraform'},
  //     {id: 'devops_jenkins', value: 'Jenkins'},
  //     {id: 'devops_github_actions', value: 'GitHub Actions'},
  //     {id: 'devops_ansible', value: 'Ansible'},
  //     {id: 'devops_prometheus', value: 'Prometheus'},
  //   ],
  // },
  // {
  //   title: 'Design',
  //   technologies: [
  //     {id: 'design_figma', value: 'Figma'},
  //     {id: 'design_sketch', value: 'Sketch'},
  //     {id: 'design_adobexd', value: 'Adobe XD'},
  //     {id: 'design_photoshop', value: 'Photoshop'},
  //     {id: 'design_illustrator', value: 'Illustrator'},
  //     {id: 'design_framer', value: 'Framer'},
  //     {id: 'design_invision', value: 'InVision'},
  //     {id: 'design_zeplin', value: 'Zeplin'},
  //     {id: 'design_principle', value: 'Principle'},
  //     {id: 'design_aftereffects', value: 'After Effects'},
  //   ],
  // },
  // {
  //   title: 'QA',
  //   technologies: [
  //     {id: 'qa_jest', value: 'Jest'},
  //     {id: 'qa_cypress', value: 'Cypress'},
  //     {id: 'qa_maestro', value: 'Maestro'},
  //     {id: 'qa_selenium', value: 'Selenium'},
  //     {id: 'qa_playwright', value: 'Playwright'},
  //     {id: 'qa_mocha', value: 'Mocha'},
  //     {id: 'qa_testcafe', value: 'TestCafe'},
  //     {id: 'qa_appium', value: 'Appium'},
  //     {id: 'qa_postman', value: 'Postman'},
  //     {id: 'qa_junit', value: 'JUnit'},
  //   ],
  // },
  // {
  //   title: 'Architecture',
  //   technologies: [
  //     {id: 'architecture_monorepo', value: 'Monorepo'},
  //     {id: 'architecture_turborepo', value: 'Turborepo'},
  //     {id: 'architecture_microfrontend', value: 'Micro Frontends'},
  //     {id: 'architecture_serverless', value: 'Serverless'},
  //     {id: 'architecture_event_driven', value: 'Event-Driven Architecture'},
  //   ],
  // },
]
